### ISSUE TITLE
Fatal Error :: Admin

### ISSUE THREAD

**Issue by jksimoniii** [classyllama/ClassyLlama_AvaTax#7]
When accessing admin homepage I see the following error

```
Fatal error: Arrays are not allowed in class constants in vendor/classyllama/module-avatax/Helper/Config.php on line 138
```

Here is my PHP version

```
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

**Comment by erikhansen** [comment]
@jksimoniii It looks like we're using a PHP 5.6-only feature. I'll change this in the code and push out a new release shortly.

**Comment by erikhansen** [comment]
@jksimoniii I just pushed a fix to https://github.com/classyllama/ClassyLlama_AvaTax/commit/0ac861da77e0b4739fe92c321e69db890452b2fd Before pushing out a new release, would you be able to test this to ensure it solves your issue? You should be able to get the latest code by running `composer update classyllama/module-avatax:dev-master`

**Comment by jksimoniii** [comment]
Still throws an error.  Doesn't look like that file changed.

```
composer update classyllama/module-avatax:dev-master
Package "classyllama/module-avatax:dev-master" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)                    
Nothing to install or update
Generating autoload files
```

```
Fatal error: Arrays are not allowed in class constants in /vendor/classyllama/module-avatax/Helper/Config.php on line 138
```

```
/**
     * List of countries that are enabled by default
     */
    const TAX_CALCULATION_COUNTRIES_DEFAULT = ['US', 'CA'];
```

**Comment by erikhansen** [comment]
@jksimoniii Sorry, I gave you the wrong command to update the extension. Try this: `composer update classyllama/module-avatax`

**Comment by jksimoniii** [comment]
Thanks!  Marking as resolved.
